# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rebbix Website
email: hello@rebbix.com
description: Rebbix Website
url: "http://rebbix.com" # the base hostname & protocol for your site
# baseurl: "/omg"
twitter_username: rebbix
github_username:  rebbix

# Build settings
markdown: kramdown

collections:
- work
- team
- life

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
