# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rebbix
email: hello@rebbix.com
description: Rebbix Website
url: "https://rebbix.com" # the base hostname & protocol for your site
twitter_username: rebbix
github_username:  rebbix

# Build settings
markdown: kramdown

collections:
- work
- team
- life

exclude:
  - .dockerignore
  - .eslintrc.js
  - .gitignore
  - .ruby-version
  - config.ru
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - yarn.lock
  - vendor
  - node_modules
