version: "3"
services:
  app:
    build:
      context: .
      args: &ENV
        JEKYLL_ENV: development
    command: jekyll serve
    volumes:
      - .:/build
    ports:
      - "4000:4000"
    environment:
      << : *ENV
